.cvp_js_metadata <- function() {
deps_metadata <- list(`cvp` = structure(list(name = "cvp",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-cornerstoneVP.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "cvp",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`cvp` = structure(list(name = "cvp",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-cornerstoneVP.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "cvp",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`cvp` = structure(list(name = "cvp",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'cvp.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "cvp",
all_files = FALSE), class = "html_dependency"),
`cvp` = structure(list(name = "cvp",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'cvp.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "cvp",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"))
return(deps_metadata)
}
